### ISSUE TITLE
Importing wishlists gets altered when item is added

### ISSUE THREAD

**Issue by traisjames** [mlsof21/DIMWishlistBuilder#12]
I am trying to import some wishlists from [https://wishlists.littlelight.club/](https://wishlists.littlelight.club/#/) and when adding a weapon the imported items go from
```
// Gnawing Hunger - PVE (pve)
//notes: tags:pve
dimwishlist:item=821154603&perks=1392496348,2420895100,3300816228,3425386926


// Sola's Scar ()
dimwishlist:item=1313528549&perks=2827049491,52780822,1749209109,1546637391
dimwishlist:item=1313528549&perks=2827049491,52780822,1749209109,2396489472
dimwishlist:item=1313528549&perks=2827049491,52780822,1749209109,2726471870


// Trustee - High Ammo ()
dimwishlist:item=1392919471&perks=3661387068,2420895100,1523832109,3592538738
dimwishlist:item=1392919471&perks=4090651448,2420895100,1523832109,3592538738
dimwishlist:item=1392919471&perks=1482024992,2420895100,1523832109,3592538738
```

to 

```
// Gnawing Hunger - PVE (pve)
//notes:tags:pve
dimwishlist:item=821154603&perks=1392496348,2420895100,3300816228,3425386926

// 
//notes:ee - High Ammo ()
dimwishlist:item=1392919471&perks=3661387068,2420895100,1523832109,3592538738
dimwishlist:item=1392919471&perks=4090651448,2420895100,1523832109,3592538738
dimwishlist:item=1392919471&perks=1482024992,2420895100,1523832109,3592538738
```

This happens on larger lists too, where items between a double line return get removed and notes get trimmed.  Another example starts with
```
// Seventh Seraph SAW - Without Warrig ()
dimwishlist:item=2582755344&perks=3661387068,1968497646,3300816228,1546637391
dimwishlist:item=2582755344&perks=3661387068,1561002382,3300816228,1546637391
dimwishlist:item=2582755344&perks=1392496348,1968497646,3300816228,1546637391
dimwishlist:item=2582755344&perks=1392496348,1561002382,3300816228,1546637391
```

and becomes

```
// Seventh Seraph SAW - Without Warrig ()
//notes:ist:item=2582755344&perks=3661387068,1968497646,3300816228,1546637391
dimwishlist:item=2582755344&perks=3661387068,1561002382,3300816228,1546637391
dimwishlist:item=2582755344&perks=1392496348,1968497646,3300816228,1546637391
dimwishlist:item=2582755344&perks=1392496348,1561002382,3300816228,1546637391
```

**Comment by mlsof21** [comment]
@traisjames I just submitted a new build for review. So hopefully the fix works. Any list that wasn't made initially through the extension could have some issues. I hadn't actually tried importing another list, so this is a good test. I'll keep this issue open just in case there continue to be errors when importing.

**Comment by traisjames** [comment]
Ok.  I would suggest trying https://wishlists.littlelight.club/#/ to build a test list or download one of the DIM prebuilt ones.  I like the littlelight one just because I can select multiple perks at once and have them all created, at once, and I can add names and such but Gunsmith is much better for finding weapons.  Plus littlelight is no longer being updated.

**Comment by traisjames** [comment]
Looks better.  Looks like your code expects...one with the name and one with the notes.  
<img width="1422" alt="Screen Shot 2022-02-27 at 1 25 34 AM" src="https://user-images.githubusercontent.com/751219/155872867-1d7d3fb5-2db6-4848-beac-8cb4e3786f3f.png">

```
function parseTextarea() {
  const text = document.getElementById("wishlistTextarea").value;
  const weapons = text.split("\n\n").filter((t) => t);
  rolls = {};
  for (const weapon of weapons) {
    const items = weapon.trim().split("\n");
    let startid = 0;
    for (const item of items){
      if (item.substr(17) == "dimwishlist:item=") {
        const weaponRolls = items.slice(startid);  //start of items list
        break;
     } else { //current line is not items
       startid++; 
     }

    //Don't add back a weapon if it doesn't have any rolls
    if (weaponRolls && weaponRolls.length > 0) {
      let weaponHash =
        weaponRolls[0].indexOf("&") >= 0
          ? weaponRolls[0].split("&")[0].substr(17)
          : weaponRolls[0].substr(17);
      if (weaponHash.indexOf("-") === 0) {
        weaponHash = weaponHash.substr(1);
      }

      const weaponKey = items[0].substr(3);
      const notes = items[1];  //Unless making new note, leave line as is.
      rolls[weaponKey] = {};
      rolls[weaponKey]["name"] = weaponMap[weaponHash];
      rolls[weaponKey]["notes"] = notes;
      rolls[weaponKey]["rolls"] = weaponRolls;
    }
  }
}
```
Probably wont work off the bat (its also years since I did JS) and might need more to put back 3 or more notes should that happen, but if there is already a line that does not start with "dimwishlist:item=" then maybe it can be left alone?

**Comment by mlsof21** [comment]
> Ok. I would suggest trying https://wishlists.littlelight.club/#/ to build a test list or download one of the DIM prebuilt ones. I like the littlelight one just because I can select multiple perks at once and have them all created, at once, and I can add names and such but Gunsmith is much better for finding weapons. Plus littlelight is no longer being updated.

I do intend on adding a permutation feature. I can't allow D2Gunsmith to select multiple perks, but I can probably do something by taking each perks in a created list for a weapon, then permute off that. Definitely  a future feature.

**Comment by mlsof21** [comment]
While not perfect, the import will handle most formats of wishlists at this point.
